platform: linux
image_resource:
  type: docker-image
  source: {repository: khulnasoft-lab/concourse}
inputs:
- name: khulnasoft-lab
run:
  path: khulnasoft-lab/concourse/tasks/promote-lambda/run.bash
params:
  AWS_ACCESS_KEY_ID: ((aws_access_key_id))
  AWS_SECRET_ACCESS_KEY: ((aws_access_key_secret))
