platform: linux
image_resource:
  type: docker-image
  source: {repository: khulnasoft-lab/concourse}
inputs:
- name: khulnasoft-lab
- name: meta
- name: release_bin
run:
  path: khulnasoft-lab/concourse/tasks/release-client-build/run.bash
params:
  RELEASE_DB_URI: ((release_db_uri))
  PERCENTAGE: ((percentage))
