platform: linux
image_resource:
  type: docker-image
  source: {repository: puppet/puppet-bolt}

inputs:
- name: khulnasoft-lab
outputs:
- name: build

run:
  path: khulnasoft-lab/concourse/tasks/build-puppet/run.bash
