apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfserving-fastnode.fullname" . }}
  labels:
    {{- include "tfserving-fastnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8500
  selector:
    {{- include "tfserving-fastnode.selectorLabels" . | nindent 4 }}
