image:
	GOOS=linux go build github.com/khulnasoft-lab/fastnode/fastnode-go/lang/python/cmds/import-graph-viewer
	docker build -t XXXXXXX/import-graph-viewer .

push:
	docker push XXXXXXX/import-graph-viewer
