platform: linux
image_resource:
  type: docker-image
  source: {repository: khulnasoft-lab/concourse}
inputs:
- name: khulnasoft-lab
outputs:
- name: build
run:
  path: khulnasoft-lab/concourse/tasks/build-lambda/run.bash
