platform: linux
image_resource:
  type: docker-image
  source: {repository: khulnasoft-lab/concourse}

inputs:
- name: khulnasoft-lab
- name: ((build))

outputs:
- name: tfvars

params:
  VERSIONS: ((versions))
  BUILD: ((build))

run:
  path: khulnasoft-lab/concourse/tasks/tf-vars/run.bash
