- module: nginx
  #metricsets:
  #  - stubstatus
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1:8080"]

  # Path to server status. Default server-status
  server_status_path: "nginx_status"
